export const STATUS_FETCHING = 'STATUS_FETCHING';
export const STATUS_FAILURE = 'STATUS_FAILURE';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';

export const VALIDATE_ADDRESS_INIT = '@@address/VALIDATE_ADDRESS_INIT';
export const VALIDATE_ADDRESS_FAILURE = '@@address/VALIDATE_ADDRESS_FAILURE';
export const VALIDATE_ADDRESS_SUCCESS = '@@address/VALIDATE_ADDRESS_SUCCESS';

export const DELETE_STOP = '@@stop/DELETE_STOP';
